### PR TITLE
Go faster. Literally.

### PR DESCRIPTION
**Pull request by RealPacket**
This PR will focus on hosting stuff locally so that browsers will cache it. For privacy reasons, the browsers don't use the cache for CORS requests.
This seems to help with the speed index, LCP, and FCP in Lighthouse.
It also removes the need of the OPTIONS request sent by browsers to see if the origin has permission to send the request.

- [x] Locally host some stuff
  - [x] Save some bytes
    - [x] Convert some images to formats like WebP or JPEG
    - [x] Compression with brotli and other compression stuff
  - [x] Font
    - [x] Host the CSS locally
    - [x] Host the font locally

### CODE REVIEW

**Comment by RealPacket** [comment]
Lighthouse score preview:
image

**Comment by RealPacket** [comment]
Current preview:
image

**Comment by RealPacket** [comment]
Here's the settings I was using:
image

**Comment by RealPacket** [comment]
Mobile lighthouse report (the only extensions I had on the test is uBlock Origin):
image

**Comment by RealPacket** [comment]
Lighthouse report without uBlock Origin:
image

**Comment by RealPacket** [comment]
Lighthouse report:
image
Lighthouse report without uBlock Origin:
image

**Comment by GStudiosX2** [comment]
https://www.npmjs.com/package/@fontsource/lexend?activeTab=readme
You could've used the fontsource but it doesn't really matter I'll merge it

**Comment by RealPacket** [comment]
> https://www.npmjs.com/package/@fontsource/lexend?activeTab=readme You could've used the fontsource but it doesn't really matter I'll merge it

Didn't know about the package.

**Pull request merged**
