### PR TITLE
feat(e2e-encryption): add encryption libraries

### PR DESCRIPTION
**Pull request by RealPacket**
This adds end-to-end encryption to the messages feature.
I took the libraries from https://github.com/GetStream/encrypted-web-chat/tree/main/src/lib/, but ported to TypeScript.
Based on https://github.com/GetStream/encrypted-web-chat/, except that we're not using their crappy service. We're just taking their encryption and applying it to our code.

- [x] Add encryption libraries
- [ ] Actually encrypt stuff.

### CODE REVIEW

**Comment by GStudiosX2** [comment]
One thing from that example that I would not like to take is where you have to save your keys I don't want to store it on the client either because I wouldn't want people to not be able to decrypt their messages if they are in an incognito tab or on a different device I hope that makes sense ? I don't know much about encryption or e2ee though

**Comment by RealPacket** [comment]
> One thing from that example that I would not like to take is where you have to save your keys I don't want to store it on the client either because I wouldn't want people to not be able to decrypt their messages if they are in an incognito tab or on a different device I hope that makes sense ? I don't know much about encryption or e2ee though

If we don't store it on the client, then doesn't that mean we will lose our previous conversation history, because after you lose the private key, then you can't decrypt the previous messages.
So, we'll need to store it. However, it won't persist on to incognito tabs, because incognito tabs don't save or use any saved cookies, or anything a webpage has stored. Not even cache.

**Comment by RealPacket** [comment]
> One thing from that example that I would not like to take is where you have to save your keys I don't want to store it on the client either because I wouldn't want people to not be able to decrypt their messages if they are in an incognito tab or on a different device I hope that makes sense ? I don't know much about encryption or e2ee though
> 
> Edit: though I guess storing the keys in the database even if they are encrypted as well may defeat the point of e2ee but I think it's more annoying to have to save your keys
> 
> Edit2: also like I don't know how message history would work if it wasn't stored in the database?

The server would have the encrypted message history, and give it off to the clients, the clients would decrypt the contents of the messages, and display it on the webpage.

**Comment by GStudiosX2** [comment]
> > One thing from that example that I would not like to take is where you have to save your keys I don't want to store it on the client either because I wouldn't want people to not be able to decrypt their messages if they are in an incognito tab or on a different device I hope that makes sense ? I don't know much about encryption or e2ee though
> 
> If we don't store it on the client, then doesn't that mean we will lose our previous conversation history, because after you lose the private key, then you can't decrypt the previous messages.
> So, we'll need to store it. However, it won't persist on to incognito tabs, because incognito tabs don't save or use any saved cookies, or anything a webpage has stored. Not even cache.

You probably can login to your account in an incognito tab

**Comment by GStudiosX2** [comment]
> > One thing from that example that I would not like to take is where you have to save your keys I don't want to store it on the client either because I wouldn't want people to not be able to decrypt their messages if they are in an incognito tab or on a different device I hope that makes sense ? I don't know much about encryption or e2ee though
> > 
> > Edit: though I guess storing the keys in the database even if they are encrypted as well may defeat the point of e2ee but I think it's more annoying to have to save your keys
> > 
> > Edit2: also like I don't know how message history would work if it wasn't stored in the database?
> 
> The server would have the encrypted message history, and give it off to the clients, the clients would decrypt the contents of the messages, and display it on the webpage.
> If it wasn't stored, we could either:
> 1. Discard the message, it's bogus anyways.
> 2. Probably just give the encrypted contents. (maybe we should allow people to save their private key if they want)

Where would it even store the keys on the client?  Can't really do it in cookies or local storage because then there's a chance the user might clean them and then lose their messages and local storage/cookies I think is also insecure ?

**Comment by RealPacket** [comment]
Although I do think that if we do allow reporting messages, we should have a toggle when you're reporting the user that gives the keys to decrypt the previous messages, but regenerates the keys for the new messages.
Not sure about it though, because we could just allow the user to select a range of messages, but then someone could abuse the API to create false reports.

**Comment by GStudiosX2** [comment]
> Although I do think that if we do allow reporting messages, we should have a toggle when you're reporting the user that gives the keys to decrypt the previous messages, but regenerates the keys for the new messages.
> Not sure about it though, because we could just allow the user to select a range of messages, but then someone could abuse the API to create false reports.

You can generate a key per message that can be decrypted by the private key the client I guess for reporting could decrypt it then send that to decrypt the message

**Comment by RealPacket** [comment]
> > > One thing from that example that I would not like to take is where you have to save your keys I don't want to store it on the client either because I wouldn't want people to not be able to decrypt their messages if they are in an incognito tab or on a different device I hope that makes sense ? I don't know much about encryption or e2ee though
> > > Edit: though I guess storing the keys in the database even if they are encrypted as well may defeat the point of e2ee but I think it's more annoying to have to save your keys
> > > Edit2: also like I don't know how message history would work if it wasn't stored in the database?
> > 
> > 
> > The server would have the encrypted message history, and give it off to the clients, the clients would decrypt the contents of the messages, and display it on the webpage.
> > If it wasn't stored, we could either:
> > 
> > 1. Discard the message, it's bogus anyways.
> > 2. Probably just give the encrypted contents. (maybe we should allow people to save their private key if they want)
> 
> Where would it even store the keys on the client? Can't really do it in cookies or local storage because then there's a chance the user might clean them and then lose their messages and local storage/cookies I think is also insecure ? I read online not to store them there I think anyway
> 
> Also how does the other user get the key to decrypt the message in the first place

I think they exchange their public keys or something and then somehow the other user derives a private key. Not sure because I haven't implemented it yet.

**Comment by GStudiosX2** [comment]
L
> > > 1. Discard the message, it's bogus anyways.
> > > 2. Probably just give the encrypted contents. (maybe we should allow people to save their private key if they want)
> > 
> > Where would it even store the keys on the client? Can't really do it in cookies or local storage because then there's a chance the user might clean them and then lose their messages and local storage/cookies I think is also insecure ? I read online not to store them there I think anyway
> > 
> > Also how does the other user get the key to decrypt the message in the first place
> 
> I think they exchange their public keys or something and then somehow the other user derives a private key. Not sure because I haven't implemented it yet.

I'm not sure either but how would they even share their public keys and where would we store the public & private keys because you do need them and I also don't want to have an annoyance of saving your keys

**Comment by RealPacket** [comment]
> > > > 1. Discard the message, it's bogus anyways.
> > > > 2. Probably just give the encrypted contents. (maybe we should allow people to save their private key if they want)
> > > 
> > > 
> > > Where would it even store the keys on the client? Can't really do it in cookies or local storage because then there's a chance the user might clean them and then lose their messages and local storage/cookies I think is also insecure ? I read online not to store them there I think anyway
> > > Also how does the other user get the key to decrypt the message in the first place
> > 
> > 
> > I think they exchange their public keys or something and then somehow the other user derives a private key. Not sure because I haven't implemented it yet.
> 
> I'm not sure either but how would they even exchange their public keys and where would we store the public & private keys because you do need them and I also don't want to have an annoyance of saving your keys

Saving your private keys to a file should be an option that should be there as long as you have a private key.

**Comment by RealPacket** [comment]
Anyways, I'm going to try and stop yapping about the encryption so that I can get it done.

**Comment by GStudiosX2** [comment]
> > > > > 1. Discard the message, it's bogus anyways.
> > > > > 2. Probably just give the encrypted contents. (maybe we should allow people to save their private key if they want)
> > > > 
> > > > 
> > > > Where would it even store the keys on the client? Can't really do it in cookies or local storage because then there's a chance the user might clean them and then lose their messages and local storage/cookies I think is also insecure ? I read online not to store them there I think anyway
> > > > Also how does the other user get the key to decrypt the message in the first place
> > > 
> > > 
> > > I think they exchange their public keys or something and then somehow the other user derives a private key. Not sure because I haven't implemented it yet.
> > 
> > I'm not sure either but how would they even exchange their public keys and where would we store the public & private keys because you do need them and I also don't want to have an annoyance of saving your keys
> 
> Saving your private keys to a file should be an option that should be there as long as you have a private key.

Yeah but that's kinda annoying still when I go to a messaging service I would like it to when I login have all my messages there etc and not have to do anything extra

**Comment by GStudiosX2** [comment]
No clue what face wants though

**Comment by GStudiosX2** [comment]
I'll leave you alone now though so you can get stuff done xd

**Comment by RealPacket** [comment]
I need to send the key every 5 seconds or so until the client ACKs it via another HTTP request, so that the recipient will know the key.

**Comment by RealPacket** [comment]
Unless there's a way to know when the user connects to the SSE.
Then we'd probably do that except send the key every 15 seconds or more until the client ACKs it.

**Comment by GStudiosX2** [comment]
> Unless there's a way to know when the user connects to the SSE.
> Then we'd probably do that except send the key every 15 seconds or more until the client ACKs it.

I'm not exactly sure but the public keys should be fine to store I think

**Comment by GStudiosX2** [comment]
I did find some posts though that may help:

https://www.qed42.com/insights/developing-a-real-time-secure-chat-application-like-whatsapp-signal-with-end-to-end-encryption
https://crypto.stackexchange.com/questions/75217/end-to-end-encrypted-web-chat-app-with-stored-messages-in-database
https://getstream.io/blog/end-to-end-encrypted-chat-in-flutter/ (this one has some information about e2ee but it just uses their own service at the end)

**Comment by RealPacket** [comment]
I've rebased.

**Comment by GStudiosX2** [comment]
I accidentally pressed the request for review button

**Review by GStudiosX2 — COMMENTED** [review]
I accidentally pressed the request for review button

**Review by GStudiosX2 — COMMENTED** [review]
Face said we don't need this anymore but could still be worked on maybe in the future

**Pull request closed without merging**
